spring:
  application:
    name: ai-agent
  datasource:
    username: root
    password: 1111
    url: jdbc:mysql://localhost:3306/ai_agent?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    dashscope:
      api-key: sk-c1c3400e29494cfe9d73fe418a2bdd99
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json



  profiles:
    active: local
toolcallback:
  enabled:

server:
  port: 8080
  address: 0.0.0.0


# springdoc-openapi项目配置，接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cosmos.aiagent.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn



# MyBatis-Plus 配置
mybatis-plus:
  # MyBatis-Plus 配置项
  configuration:
    # 是否开启驼峰命名自动映射，即从经典数据库列名 A_COLUMN 映射到经典 Java 属性名 aColumn
    map-underscore-to-camel-case: false    # 不开启驼峰命名自动映射
  # Mapper XML 文件的位置
  mapper-locations: classpath*:mapper/*.xml
  # 实体类的包路径，用于指定实体类的别名
  type-aliases-package: com.cosmos.aiagent.pojo   # 实体类所在的包路径，指定后可以使用实体类名作为别名


mcpTools:
  searchTool:
    apiKey: HDQJJBsCG7pwHMhNj2dJFfCG